### PR TITLE
Js okta 415796 disable token lifetime validation

### PR DESCRIPTION
**Pull request by jpspringall**
PR for: [https://github.com/okta/okta-auth-js/issues/879](url)

### CODE REVIEW

**Comment by shuowu** [comment]
@jpspringall Thanks for the PR! While our team is reviewing the PR, can you please sign and submit a CLA for us? https://developer.okta.com/cla/

**Comment by shuowu** [comment]
Internal Ref: OKTA-417253

Relates to issue #879

**Comment by jpspringall** [comment]
> @jpspringall Thanks for the PR! While our team is reviewing the PR, can you please sign and submit a CLA for us? https://developer.okta.com/cla/

Hi @shuowu I have submitted a CLA, also confirming that master is the correct target branch?

Thanks

James

**Comment by shuowu** [comment]
@jpspringall Yes, it's master.

**Review by shuowu — APPROVED** [review]

**Comment by jpspringall** [comment]
I think this can be closed now, looks as it's been included in 5.5

**Pull request closed without merging**
