### PR TITLE
Add travis build status badge

### PR DESCRIPTION
**Pull request by haishengwu-okta**
- add travis build badge for master branch.
- turns out travis is not building any branches except PRs according the [travis build page](https://travis-ci.org/okta/okta-auth-js/)

### CODE REVIEW

**Comment by rchild-okta** [comment]
@jmaldonado-okta do you know why we're not building other branches in Travis (specifically, master)?

**Comment by rchild-okta** [comment]
@Ujjwalreddy-okta we should also add this to [okta-signin-widget](https://github.com/okta/okta-signin-widget)

**Comment by jmaldonado-okta** [comment]
@rchild-okta for two main reasons but it can be changed if desired:
1. We are under freemium model meaning our Travis resources are limited. We mitigate queues by building only on PR creation instead of with every push.
2. Considering that a push to branch master happens after the PR has been reviewed and passed Travis plus, since we test builds from branch master internally (Bacon), then building it on Travis seemed redundant at the time.

Btw, only master is tested by Bacon to mitigate potential security risks.

**Reference:** https://oktawiki.atlassian.net/wiki/display/eng/Okta+Public+CI%3A+Travis

**Comment by rchild-okta** [comment]
@jmaldonado-okta ah, I see. So, the one thing that would be nice to have (which this PR is attempting to add) is the badge that tells whether the travis build is passing or not. It looks like the badge status is tied to master. Since our travis usage is low right now, can we enable it for master as well as external pull requests?

And, if we start hitting limits in the future, deciding then to shut off topic branch builds from Travis.

**Comment by jmaldonado-okta** [comment]
@rchild-okta it already has it unless I am misunderstanding what you guys are looking for.

Click on _Show all checks_ and that will expand and show the Travis CI result for this specific PR. I believe by default Github will expand it automatically only if there were failures.

Once in the status check, you could click on Details and that will take you to Travis for details about this particular run.

If this is not what you guys are looking for or expecting, can we sync up and clarify?

**Comment by haishengwu-okta** [comment]
@jmaldonado-okta the "Show all checks" is the status for this PR. what we wish to have to an building status badge for master. 
like the `linux | passing`, `window | passing` from readme of https://github.com/expressjs/express

**Comment by jmaldonado-okta** [comment]
@haishengwu-okta Got it. Lets sync up to wrap the req since there are different options and implications for each. I will schedule it.

**Comment by rchild-okta** [comment]
@haishengwu-okta, @jmaldonado-okta updated TravisCi to run topic/master branches now, so it should work now (once we have our first master commit). 🚀 !

**Comment by haishengwu-okta** [comment]
Nice! so we would hope after merge this PR, there will be an green badge in the readme.

**Comment by haishengwu-okta** [comment]
@rchild-okta @lboyette-okta would you help to merge?

**Pull request merged**
