### PR TITLE
feat: remove value field from token - OKTA-338251

### PR DESCRIPTION
**Pull request by shuowu**
As this PR changes the token type, it still looks like a breaking change.

### CODE REVIEW

**Comment by aarongranick-okta** [comment]
> As this PR changes the token type, it still looks like a breaking change.

Please base the branch/PR against the `dev-5.0` branch.

**Comment by aarongranick-okta** [comment]
@shuowu what happened to the `dev-5.0` branch? I am seeing that it is even with master. It should have package.json bumped to version 5.0.0

**Comment by shuowu** [comment]
> @shuowu what happened to the `dev-5.0` branch? I am seeing that it is even with master. It should have package.json bumped to version 5.0.0

I re-created it since your last one has the `memory` change in. I'll bump the version from `dev-5.0`

**Review by swiftone — APPROVED** [review]

**Comment by Primajin** [comment]
May I ask what the reasoning behind this change was since I can't read your  OKTA-338251. And the workaround / migration should look like?

**Comment by shuowu** [comment]
@Primajin It's the same. the value field is removed to fix size limit issue for cookie storage.

**Pull request merged**
