### PR TITLE
Use /.well-known/openid-configuration issuer attribute for id_token validation

### PR DESCRIPTION
**Pull request by JamesParkinSonos**
This change is based on a previous pull request made by @scottirvinsonos (https://github.com/okta/okta-auth-js/pull/555), however, his implementation seems to have been lost when the code was refactored.

---

Other Okta SDK's use the issuer URL found in the /.well-known/openid-configuration response body when validating the id_token. This SDK currently uses the URL specified in the config object passed to the constructor at the time the OAuth client object is instantiated. This is not desirable as it makes it impossible to use a proxy with Okta.

The change made uses the issuer attribute found in the /.well-known/openid-configuration response body and compares it to the issuer claim in the id_token to validate the token.

### CODE REVIEW

**Comment by shuowu** [comment]
@JamesParkinSonos Thanks for the PR! While our team is reviewing the PR, can you please sign and submit a CLA for us? https://developer.okta.com/cla/

**Comment by JamesParkinSonos** [comment]
Thanks @shuowu. I've signed and emailed the CLA.

**Comment by shuowu** [comment]
Internal Ref: OKTA-412050

**Comment by shuowu** [comment]
@JamesParkinSonos I just figured out the issue is actually handled by one of our internal PR (https://github.com/okta/okta-auth-js/pull/858). Thanks again for your contribution!

Close the PR.

**Pull request closed without merging**
